set1 = set()
set2 = set()
for i in range(1,11):
   set1.add(i*i)
   set2.add(i*i*i)
print("the square of set = ",set1)
print("the cube of set = ",set2)
a=set1.pop()
print("poped element from set1 is: ",a)
set2.remove(27)
print("deletion of 27 and set becomes=",set2)
set1.update(set2)
print("after updated set is = ",set1)
set1.clear()
print(" clear value set is = ",set1)
